import { useEffect, useMemo, useRef, useState } from "react";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport, type UIMessage } from "ai";
import { Link, useNavigate, useParams } from "@tanstack/react-router";
import { Bot, LogOut, Menu, MessageSquarePlus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Conversation, ConversationContent, ConversationEmptyState, ConversationScrollButton } from "@/components/ai-elements/conversation";
import { Message, MessageContent, MessageResponse } from "@/components/ai-elements/message";
import { PromptInput, PromptInputFooter, PromptInputSubmit, PromptInputTextarea } from "@/components/ai-elements/prompt-input";
import { Shimmer } from "@/components/ai-elements/shimmer";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { supabase } from "@/integrations/supabase/client";
import { BrandLogo } from "./brand-logo";

type Thread = { id: string; title: string; updated_at: string };

async function loadSession() { const { data } = await supabase.auth.getSession(); return data.session; }

export function AdvisorLanding() {
  const navigate = useNavigate();
  useEffect(() => { void (async () => { const session = await loadSession(); if (!session) { void navigate({ to: "/acceso" }); return; } const { data } = await supabase.from("chat_threads").select("id").order("updated_at", { ascending: false }).limit(1); if (data?.[0]) { void navigate({ to: "/asesor/$threadId", params: { threadId: data[0].id } }); return; } const { data: created, error } = await supabase.from("chat_threads").insert({ user_id: session.user.id }).select("id").single(); if (error || !created) { toast.error("No pudimos iniciar la conversación."); return; } void navigate({ to: "/asesor/$threadId", params: { threadId: created.id } }); })(); }, [navigate]);
  return <main className="flex min-h-screen items-center justify-center bg-secondary"><Shimmer className="text-primary">Preparando tu espacio privado…</Shimmer></main>;
}

export function AdvisorThreadPage() {
  const { threadId } = useParams({ from: "/asesor/$threadId" });
  const navigate = useNavigate(); const [sessionToken, setSessionToken] = useState(""); const [userId, setUserId] = useState(""); const [threads, setThreads] = useState<Thread[]>([]); const [initial, setInitial] = useState<UIMessage[] | null>(null); const [mobileOpen, setMobileOpen] = useState(false);
  async function refreshThreads() { const { data } = await supabase.from("chat_threads").select("id,title,updated_at").order("updated_at", { ascending: false }); setThreads(data ?? []); }
  useEffect(() => { void (async () => { const session = await loadSession(); if (!session) { void navigate({ to: "/acceso" }); return; } setSessionToken(session.access_token); setUserId(session.user.id); await refreshThreads(); const { data, error } = await supabase.from("chat_messages").select("id,role,parts").eq("thread_id", threadId).order("created_at"); if (error) { toast.error("Esta conversación no está disponible."); void navigate({ to: "/asesor" }); return; } setInitial((data ?? []).map((row) => ({ id: row.id, role: row.role as "user" | "assistant", parts: row.parts as UIMessage["parts"] }))); })(); }, [threadId, navigate]);
  async function createThread() { if (!userId) return; const { data, error } = await supabase.from("chat_threads").insert({ user_id: userId }).select("id").single(); if (error || !data) { toast.error("No pudimos crear la conversación."); return; } setMobileOpen(false); void navigate({ to: "/asesor/$threadId", params: { threadId: data.id } }); }
  async function removeThread(id: string) { await supabase.from("chat_threads").delete().eq("id", id); const remaining = threads.filter((t) => t.id !== id); if (id === threadId) { if (remaining[0]) void navigate({ to: "/asesor/$threadId", params: { threadId: remaining[0].id } }); else await createThread(); } else setThreads(remaining); }
  if (!initial || !sessionToken) return <main className="flex min-h-screen items-center justify-center bg-secondary"><Shimmer className="text-primary">Abriendo conversación…</Shimmer></main>;
  return <AdvisorShell key={threadId} threadId={threadId} token={sessionToken} threads={threads} onCreate={createThread} onDelete={removeThread} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen} initial={initial} refreshThreads={refreshThreads} />;
}

function AdvisorShell({ threadId, token, threads, onCreate, onDelete, mobileOpen, setMobileOpen, initial, refreshThreads }: { threadId: string; token: string; threads: Thread[]; onCreate: () => void; onDelete: (id: string) => void; mobileOpen: boolean; setMobileOpen: (v: boolean) => void; initial: UIMessage[]; refreshThreads: () => Promise<void> }) {
  const input = useRef<HTMLTextAreaElement>(null);
  const transport = useMemo(() => new DefaultChatTransport({ api: "/api/chat", headers: { Authorization: `Bearer ${token}` }, body: { threadId } }), [token, threadId]);
  const { messages, sendMessage, status, stop } = useChat({ id: threadId, messages: initial, transport, onError: (error) => toast.error(error.message), onFinish: () => { void refreshThreads(); input.current?.focus(); } });
  async function submit(message: { text: string }) { if (!message.text.trim()) return; await sendMessage({ text: message.text.trim() }); input.current?.focus(); }
  const sidebar = <Sidebar threads={threads} active={threadId} onCreate={onCreate} onDelete={onDelete} close={() => setMobileOpen(false)} />;
  return <main className="flex h-screen overflow-hidden bg-background"><aside className="hidden w-72 shrink-0 border-r border-primary-foreground/10 bg-luxury text-primary-foreground md:block">{sidebar}</aside><section className="flex min-w-0 flex-1 flex-col"><header className="flex h-16 items-center justify-between border-b border-border px-4"><div className="flex items-center gap-3"><Sheet open={mobileOpen} onOpenChange={setMobileOpen}><SheetTrigger asChild><Button size="icon" variant="ghost" className="md:hidden"><Menu /></Button></SheetTrigger><SheetContent side="left" className="w-[88%] bg-luxury p-0 text-primary-foreground"><SheetTitle className="sr-only">Conversaciones</SheetTitle>{sidebar}</SheetContent></Sheet><span className="flex size-9 items-center justify-center rounded-full bg-primary text-primary-foreground"><Bot /></span><div><strong className="block text-sm">Asesor Sabas Marin</strong><span className="text-xs text-muted-foreground">Disponible 24/7</span></div></div><Button asChild variant="ghost" size="sm"><Link to="/cotizar" search={{ ramo: undefined }}>Cotizar</Link></Button></header>
    <Conversation className="mx-auto w-full max-w-3xl"><ConversationContent className="px-5 py-8">{messages.length === 0 ? <ConversationEmptyState icon={<Bot className="size-10 text-primary" />} title="¿Qué deseas proteger?" description="Puedo orientarte sobre coberturas, requisitos, pagos y pasos ante un siniestro."><div className="grid gap-2 sm:grid-cols-2">{["¿Qué necesito para cotizar salud?", "¿Cómo actúo ante una emergencia?", "Explícame AMP y Carta Aval", "Quiero proteger mi empresa"].map((q) => <Button key={q} variant="outline" className="h-auto whitespace-normal py-3 text-left" onClick={() => void sendMessage({ text: q })}>{q}</Button>)}</div></ConversationEmptyState> : messages.map((message) => <Message from={message.role} key={message.id}><MessageContent>{message.parts.map((part, i) => part.type === "text" ? <MessageResponse key={i}>{part.text}</MessageResponse> : null)}</MessageContent></Message>)}{status === "submitted" && <Shimmer className="text-sm">Analizando tu consulta…</Shimmer>}</ConversationContent><ConversationScrollButton /></Conversation>
    <div className="mx-auto w-full max-w-3xl px-4 pb-4"><PromptInput onSubmit={submit} className="bg-background shadow-lg"><PromptInputTextarea ref={input} autoFocus placeholder="Escribe tu consulta de seguros…" /><PromptInputFooter className="justify-end"><PromptInputSubmit status={status} onStop={stop} className="rounded-full" /></PromptInputFooter></PromptInput><p className="mt-2 text-center text-[11px] text-muted-foreground">Orientación general. Las condiciones finales dependen de la póliza y la aseguradora.</p></div></section></main>;
}

function Sidebar({ threads, active, onCreate, onDelete, close }: { threads: Thread[]; active: string; onCreate: () => void; onDelete: (id: string) => void; close: () => void }) { const navigate = useNavigate(); return <div className="flex h-full flex-col p-4"><Link to="/" onClick={close}><BrandLogo inverse className="h-11" /></Link><Button onClick={onCreate} className="mt-8 bg-primary-foreground text-luxury hover:bg-primary-foreground/90"><MessageSquarePlus /> Nueva conversación</Button><div className="mt-6 flex-1 space-y-1 overflow-y-auto">{threads.map((thread) => <div key={thread.id} className={`group flex items-center rounded-md ${thread.id === active ? "bg-primary-foreground/15" : "hover:bg-primary-foreground/10"}`}><button type="button" onClick={() => { close(); void navigate({ to: "/asesor/$threadId", params: { threadId: thread.id } }); }} className="min-w-0 flex-1 truncate px-3 py-3 text-left text-sm">{thread.title}</button><Button size="icon-sm" variant="ghost" aria-label="Eliminar conversación" onClick={() => onDelete(thread.id)} className="mr-1 text-primary-foreground/60 hover:bg-primary-foreground/10 hover:text-primary-foreground"><Trash2 /></Button></div>)}</div><Button variant="ghost" className="justify-start text-primary-foreground/70 hover:bg-primary-foreground/10 hover:text-primary-foreground" onClick={async () => { await supabase.auth.signOut(); void navigate({ to: "/acceso" }); }}><LogOut /> Cerrar sesión</Button></div>; }