/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as AsesorRouteImport } from './routes/asesor'
import { Route as CotizarRouteImport } from './routes/cotizar'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AsesorThreadIdRouteImport } from './routes/asesor.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesorRoute = AsesorRouteImport.update({
  id: '/asesor',
  path: '/asesor',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizarRoute = CotizarRouteImport.update({
  id: '/cotizar',
  path: '/cotizar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesorThreadIdRoute = AsesorThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AsesorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/asesor': typeof AsesorRouteWithChildren
  '/cotizar': typeof CotizarRoute
  '/api/chat': typeof ApiChatRoute
  '/asesor/$threadId': typeof AsesorThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/asesor': typeof AsesorRouteWithChildren
  '/cotizar': typeof CotizarRoute
  '/api/chat': typeof ApiChatRoute
  '/asesor/$threadId': typeof AsesorThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/asesor': typeof AsesorRouteWithChildren
  '/cotizar': typeof CotizarRoute
  '/api/chat': typeof ApiChatRoute
  '/asesor/$threadId': typeof AsesorThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/acceso' | '/asesor' | '/cotizar' | '/api/chat' | '/asesor/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/acceso' | '/asesor' | '/cotizar' | '/api/chat' | '/asesor/$threadId'
  id:
    | '__root__'
    | '/'
    | '/acceso'
    | '/asesor'
    | '/cotizar'
    | '/api/chat'
    | '/asesor/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoRoute: typeof AccesoRoute
  AsesorRoute: typeof AsesorRouteWithChildren
  CotizarRoute: typeof CotizarRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesor': {
      id: '/asesor'
      path: '/asesor'
      fullPath: '/asesor'
      preLoaderRoute: typeof AsesorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizar': {
      id: '/cotizar'
      path: '/cotizar'
      fullPath: '/cotizar'
      preLoaderRoute: typeof CotizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesor/$threadId': {
      id: '/asesor/$threadId'
      path: '/$threadId'
      fullPath: '/asesor/$threadId'
      preLoaderRoute: typeof AsesorThreadIdRouteImport
      parentRoute: typeof AsesorRoute
    }
  }
}

interface AsesorRouteChildren {
  AsesorThreadIdRoute: typeof AsesorThreadIdRoute
}

const AsesorRouteChildren: AsesorRouteChildren = {
  AsesorThreadIdRoute: AsesorThreadIdRoute,
}

const AsesorRouteWithChildren =
  AsesorRoute._addFileChildren(AsesorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoRoute: AccesoRoute,
  AsesorRoute: AsesorRouteWithChildren,
  CotizarRoute: CotizarRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
